name:                logParse
version:             0.1.0
license:             GPL-3
git:                 https://gitlab.com/metaporia/logParse
author:              "Keane Yahn-Krafft"
maintainer:          "kyahnkrafft@me.com"
copyright:           "2018 Keane Yahn-Krafft"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://gitlab.com/metaporia/logParse#README.md>

dependencies:
- base >= 4.7 && < 5
- text
- trifecta
- pretty-show
- mtl >= 2.2.2
- raw-strings-qq
- hspec
- QuickCheck
- split
- parsers
- time
- yaml-config
- aeson
- directory
- bytestring
- text-metrics
- word-wrap
- lens
- transformers
- ansi-terminal

library:
  source-dirs: src
  exposed-modules:
    - Lib
    - Parse.Entry
    - Parse
    - Helpers
    - Search
    - Render

executables:
  logParse-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - logParse
    - optparse-applicative
    - time

tests:
  logParse-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - logParse
    - hspec
    - QuickCheck
    - trifecta
